DROP TABLE IF EXISTS sports CASCADE;
DROP TABLE IF EXISTS pictures CASCADE;
DROP TABLE IF EXISTS features CASCADE;
DROP TABLE IF EXISTS colors CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS products_colors CASCADE;
DROP TABLE IF EXISTS products_features CASCADE;
DROP TABLE IF EXISTS products_sports CASCADE;

CREATE TABLE sports
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(32)                             NOT NULL,
    CONSTRAINT pk_sports PRIMARY KEY (id)
);

CREATE TABLE pictures
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uri        VARCHAR(256)                            NOT NULL,
    product_id VARCHAR(36),
    CONSTRAINT pk_pictures PRIMARY KEY (id)
);

CREATE TABLE features
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(64)                             NOT NULL,
    description VARCHAR(256)                            NOT NULL,
    CONSTRAINT pk_features PRIMARY KEY (id)
);

CREATE TABLE colors
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(64)                             NOT NULL,
    hex  VARCHAR(7)                              NOT NULL,
    CONSTRAINT pk_colors PRIMARY KEY (id)
);

CREATE TABLE products
(
    id                 VARCHAR(36)   NOT NULL,
    upc                VARCHAR(64)   NOT NULL,
    name               VARCHAR(64)   NOT NULL,
    price              DECIMAL       NOT NULL,
    discount           INTEGER,
    description        VARCHAR(1024) NOT NULL,
    brand              VARCHAR(64)   NOT NULL,
    quantity           BIGINT        NOT NULL,
    country_of_origin  VARCHAR(64),
    sizeus             INTEGER       NOT NULL,
    sizeuk             INTEGER       NOT NULL,
    sizeeur            INTEGER       NOT NULL,
    height             INTEGER       NOT NULL,
    length             INTEGER       NOT NULL,
    width              INTEGER       NOT NULL,
    weight             INTEGER       NOT NULL,
    deleted            BOOLEAN DEFAULT FALSE,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE products_colors
(
    colors_id  BIGINT      NOT NULL,
    product_id VARCHAR(36) NOT NULL,
    CONSTRAINT pk_products_colors PRIMARY KEY (colors_id, product_id)
);

CREATE TABLE products_features
(
    features_id BIGINT      NOT NULL,
    product_id  VARCHAR(36) NOT NULL,
    CONSTRAINT pk_products_features PRIMARY KEY (features_id, product_id)
);

CREATE TABLE products_sports
(
    product_id VARCHAR(36) NOT NULL,
    sports_id  BIGINT      NOT NULL,
    CONSTRAINT pk_products_sports PRIMARY KEY (product_id, sports_id)
);

ALTER TABLE pictures
    ADD CONSTRAINT uc_pictures_product UNIQUE (product_id);

ALTER TABLE pictures
    ADD CONSTRAINT FK_PICTURES_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE products_colors
    ADD CONSTRAINT fk_procol_on_color FOREIGN KEY (colors_id) REFERENCES colors (id);

ALTER TABLE products_colors
    ADD CONSTRAINT fk_procol_on_product FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE products_features
    ADD CONSTRAINT fk_profea_on_feature FOREIGN KEY (features_id) REFERENCES features (id);

ALTER TABLE products_features
    ADD CONSTRAINT fk_profea_on_product FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE products_sports
    ADD CONSTRAINT fk_prospo_on_product FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE products_sports
    ADD CONSTRAINT fk_prospo_on_sport FOREIGN KEY (sports_id) REFERENCES sports (id);

