DROP TABLE IF EXISTS sports CASCADE;
DROP TABLE IF EXISTS features CASCADE;
DROP TABLE IF EXISTS colors CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS products_colors CASCADE;
DROP TABLE IF EXISTS products_features CASCADE;
DROP TABLE IF EXISTS products_sports CASCADE;
DROP TABLE IF EXISTS product_pictures CASCADE;

CREATE TABLE products
(
    id                 VARCHAR(36)      NOT NULL,
    upc                VARCHAR(64)      NOT NULL,
    name               VARCHAR(64)      NOT NULL,
    price              DECIMAL          NOT NULL,
    discount           INTEGER,
    description        VARCHAR(1024)    NOT NULL,
    brand              VARCHAR(64)      NOT NULL,
    quantity           BIGINT           NOT NULL,
    country_of_origin  VARCHAR(64),
    sizeus             DOUBLE PRECISION NOT NULL,
    sizeuk             DOUBLE PRECISION NOT NULL,
    sizeeur            DOUBLE PRECISION NOT NULL,
    height             DOUBLE PRECISION NOT NULL,
    length             DOUBLE PRECISION NOT NULL,
    width              DOUBLE PRECISION NOT NULL,
    weight             DOUBLE PRECISION NOT NULL,
    deleted            BOOLEAN DEFAULT FALSE,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE colors
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(64)                             NOT NULL,
    hex  VARCHAR(7)                              NOT NULL,
    CONSTRAINT pk_colors PRIMARY KEY (id)
);

CREATE TABLE features
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(64)                             NOT NULL,
    description VARCHAR(256)                            NOT NULL,
    CONSTRAINT pk_features PRIMARY KEY (id)
);

CREATE TABLE sports
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(32)                             NOT NULL,
    CONSTRAINT pk_sports PRIMARY KEY (id)
);

CREATE TABLE products_colors
(
    colors_id  BIGINT      NOT NULL,
    product_id VARCHAR(36) NOT NULL,
    CONSTRAINT pk_products_colors PRIMARY KEY (colors_id, product_id)
);

CREATE TABLE products_features
(
    features_id BIGINT      NOT NULL,
    product_id  VARCHAR(36) NOT NULL,
    CONSTRAINT pk_products_features PRIMARY KEY (features_id, product_id)
);

CREATE TABLE products_sports
(
    product_id VARCHAR(36) NOT NULL,
    sports_id  BIGINT      NOT NULL,
    CONSTRAINT pk_products_sports PRIMARY KEY (product_id, sports_id)
);

CREATE TABLE product_pictures
(
    product_id VARCHAR(36)   NOT NULL,
    pictures   VARCHAR(2048) NOT NULL
);

ALTER TABLE products_colors
    ADD CONSTRAINT fk_procol_on_color FOREIGN KEY (colors_id) REFERENCES colors (id);

ALTER TABLE products_colors
    ADD CONSTRAINT fk_procol_on_product FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE products_features
    ADD CONSTRAINT fk_profea_on_feature FOREIGN KEY (features_id) REFERENCES features (id);

ALTER TABLE products_features
    ADD CONSTRAINT fk_profea_on_product FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE products_sports
    ADD CONSTRAINT fk_prospo_on_product FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE products_sports
    ADD CONSTRAINT fk_prospo_on_sport FOREIGN KEY (sports_id) REFERENCES sports (id);

-- FOR DEBUGGING ONLY
INSERT INTO colors (name, hex)
VALUES ('Black', '#000000'),
       ('White', '#FFFFFF'),
       ('Red', '#FF0000'),
       ('Green', '#00FF00'),
       ('Blue', '#0000FF'),
       ('Yellow', '#FFFF00'),
       ('Orange', '#FFA500'),
       ('Purple', '#800080'),
       ('Brown', '#A52A2A'),
       ('Grey', '#808080'),
       ('Pink', '#FFC0CB');;

INSERT INTO sports (name)
VALUES ('Soccer'),
       ('Basketball'),
       ('Baseball'),
       ('Football'),
       ('Golf'),
       ('Tennis'),
       ('Volleyball'),
       ('Hockey'),
       ('Rugby'),
       ('Swimming'),
       ('Track and Field'),
       ('Cycling'),
       ('Martial Arts'),
       ('Boxing'),
       ('Wrestling'),
       ('Gymnastics'),
       ('Diving'),
       ('Skating'),
       ('Snowboarding'),
       ('Surfing'),
       ('Skiing'),
       ('Snowmobiling'),
       ('Hunting'),
       ('Fishing'),
       ('Camping'),
       ('Hiking'),
       ('Climbing'),
       ('Running'),
       ('Yoga'),
       ('Pilates'),
       ('Crossfit'),
       ('Weightlifting'),
       ('MMA'),
       ('Archery'),
       ('Bowling'),
       ('Billiards'),
       ('Darts'),
       ('Gaming'),
       ('Paintball'),
       ('Airsoft'),
       ('Lacrosse'),
       ('Cricket'),
       ('Racquetball'),
       ('Squash'),
       ('Badminton'),
       ('Table Tennis'),
       ('Beach Volleyball'),
       ('Beach Soccer'),
       ('Beach Tennis'),
       ('Beach Handball'),
       ('Beach Rugby'),
       ('Beach Football'),
       ('Beach Basketball'),
       ('Beach Hockey'),
       ('Beach Softball'),
       ('Beach Baseball'),
       ('Beach Ultimate Frisbee'),
       ('Beach Dodgeball'),
       ('Beach Water Polo'),
       ('Beach Water Skiing'),
       ('Beach Wakeboarding'),
       ('Beach Windsurfing'),
       ('Beach Kiteboarding'),
       ('Beach Kayaking'),
       ('Beach Canoeing'),
       ('Beach Rowing'),
       ('Beach Sailing'),
       ('Beach Surfing'),
       ('Beach Stand Up Paddleboarding'),
       ('Beach Snowboarding'),
       ('Beach Snowmobiling'),
       ('Beach Skating'),
       ('Beach Biking'),
       ('Beach Skateboarding'),
       ('Beach Scootering'),
       ('Beach BMX'),
       ('Beach Frisbee'),
       ('Beach Golf'),
       ('Beach Tennis'),
       ('Beach Badminton'),
       ('Beach Table Tennis'),
       ('Beach Cricket'),
       ('Beach Lacrosse'),
       ('Beach Squash'),
       ('Beach Racquetball'),
       ('Beach Archery'),
       ('Beach Darts'),
       ('Beach Billiards'),
       ('Beach Bowling'),
       ('Beach Paintball'),
       ('Beach Airsoft'),
       ('Beach Boxing'),
       ('Beach Wrestling'),
       ('Beach Judo'),
       ('Beach Karate');

INSERT INTO features (name, description)
VALUES ('Waterproof', 'Waterproof'),
       ('Windproof', 'Windproof'),
       ('Breathable', 'Breathable'),
       ('Lightweight', 'Lightweight'),
       ('Durable', 'Durable'),
       ('Insulated', 'Insulated'),
       ('Reflective', 'Reflective'),
       ('UV Protection', 'UV Protection'),
       ('Quick Dry', 'Quick Dry'),
       ('Moisture Wicking', 'Moisture Wicking'),
       ('Anti-Odor', 'Anti-Odor'),
       ('Anti-Microbial', 'Anti-Microbial'),
       ('Anti-Static', 'Anti-Static'),
       ('Anti-UV', 'Anti-UV'),
       ('Anti-Allergenic', 'Anti-Allergenic'),
       ('Anti-Blister', 'Anti-Blister'),
       ('Anti-Fungal', 'Anti-Fungal'),
       ('Anti-Itch', 'Anti-Itch'),
       ('Anti-Slip', 'Anti-Slip'),
       ('Anti-UV', 'Anti-UV'),
       ('Anti-Wrinkle', 'Anti-Wrinkle'),
       ('Anti-Static', 'Anti-Static'),
       ('Anti-UV', 'Anti-UV'),
       ('Anti-Allergenic', 'Anti-Allergenic'),
       ('Anti-Blister', 'Anti-Blister'),
       ('Anti-Fungal', 'Anti-Fungal'),
       ('Anti-Itch', 'Anti-Itch'),
       ('Anti-Slip', 'Anti-Slip'),
       ('Anti-UV', 'Anti-UV'),
       ('Anti-Wrinkle', 'Anti-Wrinkle'),
       ('Anti-Static', 'Anti-Static'),
       ('Anti-UV', 'Anti-UV'),
       ('Anti-Allergenic', 'Anti-Allergenic'),
       ('Anti-Blister', 'Anti-Blister'),
       ('Anti-Fungal', 'Anti-Fungal'),
       ('Anti-Itch', 'Anti-Itch'),
       ('Anti-Slip', 'Anti-Slip'),
       ('Anti-UV', 'Anti-UV'),
       ('Anti-Wrinkle', 'Anti-Wrinkle'),
       ('Anti-Static', 'Anti-Static'),
       ('Anti-UV', 'Anti-UV'),
       ('Anti-Allergenic', 'Anti-Allergenic'),
       ('Anti-Blister', 'Anti-Blister'),
       ('Anti-Fungal', 'Anti-Fungal'),
       ('Anti-Itch', 'Anti-Itch'),
       ('Anti-Slip', 'Anti-Slip');

INSERT INTO products (id, upc, name, price, discount, description, brand, quantity, country_of_origin, sizeus, sizeuk,
                      sizeeur, height, length, width, weight, created_date, last_modified_date)
VALUES ('0d61332f-e5a1-49ba-ad14-41922b534fe6', '123456789012', 'Product 1', 10.00, 0.00, 'Product 1 Description',
        'Brand 1', 10, 'USA', 5, 4.5, 40, 1.00, 1.00, 1.00, 1.00, '2019-01-01 00:00:00', '2019-01-01 00:00:00'),
       ('8c5d2cfd-7652-4ac5-978e-541cce479fbd', '123456789013', 'Product 2', 20.00, 0.00, 'Product 2 Description',
        'Brand 2', 20, 'USA', 4, 3.5, 30, 2.00, 2.00, 2.00, 2.00, '2019-01-01 00:00:00', '2019-01-01 00:00:00'),
       ('7c2d34eb-6f50-460e-a291-16600a8c3130', '123456789014', 'Product 3', 30.00, 0.00, 'Product 3 Description',
        'Brand 3', 30, 'USA', 6, 7.5, 50, 3.00, 3.00, 3.00, 3.00, '2019-01-01 00:00:00', '2019-01-01 00:00:00');

INSERT INTO products_colors (colors_id, product_id)
VALUES (1, '0d61332f-e5a1-49ba-ad14-41922b534fe6'),
       (2, '0d61332f-e5a1-49ba-ad14-41922b534fe6'),
       (3, '0d61332f-e5a1-49ba-ad14-41922b534fe6'),
       (4, '8c5d2cfd-7652-4ac5-978e-541cce479fbd'),
       (5, '8c5d2cfd-7652-4ac5-978e-541cce479fbd'),
       (7, '7c2d34eb-6f50-460e-a291-16600a8c3130'),
       (8, '7c2d34eb-6f50-460e-a291-16600a8c3130'),
       (9, '7c2d34eb-6f50-460e-a291-16600a8c3130');

INSERT INTO products_features (features_id, product_id)
VALUES (1, '0d61332f-e5a1-49ba-ad14-41922b534fe6'),
       (2, '0d61332f-e5a1-49ba-ad14-41922b534fe6'),
       (3, '0d61332f-e5a1-49ba-ad14-41922b534fe6'),
       (4, '0d61332f-e5a1-49ba-ad14-41922b534fe6'),
       (5, '0d61332f-e5a1-49ba-ad14-41922b534fe6'),
       (6, '0d61332f-e5a1-49ba-ad14-41922b534fe6'),
       (7, '0d61332f-e5a1-49ba-ad14-41922b534fe6'),
       (8, '0d61332f-e5a1-49ba-ad14-41922b534fe6'),
       (9, '0d61332f-e5a1-49ba-ad14-41922b534fe6'),
       (10, '0d61332f-e5a1-49ba-ad14-41922b534fe6'),
       (11, '0d61332f-e5a1-49ba-ad14-41922b534fe6'),
       (12, '0d61332f-e5a1-49ba-ad14-41922b534fe6'),
       (13, '0d61332f-e5a1-49ba-ad14-41922b534fe6'),
       (14, '0d61332f-e5a1-49ba-ad14-41922b534fe6'),
       (15, '0d61332f-e5a1-49ba-ad14-41922b534fe6'),
       (16, '0d61332f-e5a1-49ba-ad14-41922b534fe6'),
       (17, '0d61332f-e5a1-49ba-ad14-41922b534fe6'),
       (18, '0d61332f-e5a1-49ba-ad14-41922b534fe6');

INSERT INTO products_sports (product_id, sports_id)
VALUES ('0d61332f-e5a1-49ba-ad14-41922b534fe6', 1),
       ('0d61332f-e5a1-49ba-ad14-41922b534fe6', 2),
       ('0d61332f-e5a1-49ba-ad14-41922b534fe6', 3),
       ('0d61332f-e5a1-49ba-ad14-41922b534fe6', 4),
       ('0d61332f-e5a1-49ba-ad14-41922b534fe6', 5),
       ('0d61332f-e5a1-49ba-ad14-41922b534fe6', 6),
       ('0d61332f-e5a1-49ba-ad14-41922b534fe6', 7),
       ('0d61332f-e5a1-49ba-ad14-41922b534fe6', 8),
       ('0d61332f-e5a1-49ba-ad14-41922b534fe6', 9),
       ('0d61332f-e5a1-49ba-ad14-41922b534fe6', 10),
       ('0d61332f-e5a1-49ba-ad14-41922b534fe6', 11),
       ('0d61332f-e5a1-49ba-ad14-41922b534fe6', 12),
       ('0d61332f-e5a1-49ba-ad14-41922b534fe6', 13),
       ('0d61332f-e5a1-49ba-ad14-41922b534fe6', 14),
       ('0d61332f-e5a1-49ba-ad14-41922b534fe6', 15),
       ('0d61332f-e5a1-49ba-ad14-41922b534fe6', 16),
       ('0d61332f-e5a1-49ba-ad14-41922b534fe6', 17),
       ('0d61332f-e5a1-49ba-ad14-41922b534fe6', 18),
       ('0d61332f-e5a1-49ba-ad14-41922b534fe6', 19);

