global:
    scrape_interval: 5s
    evaluation_interval: 5s

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['host.docker.internal:9090']
      
    - job_name: 'elara-gateway'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['host.docker.internal:8080']
          labels:
            application: "Elara Gateway"

    - job_name: 'elara-eureka'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['host.docker.internal:8761']
          labels:
            application: "Elara Eureka"

    - job_name: 'elara-admin-console'
      metrics_path: '/api/actuator/prometheus'
      static_configs:
        - targets: ['host.docker.internal:8083']
          labels:
            application: "Elara Admin Console"

    - job_name: 'elara-delivery'
      metrics_path: '/api/actuator/prometheus'
      static_configs:
        - targets: ['host.docker.internal:8089']
          labels:
            application: "Elara Delivery"

    - job_name: 'elara-email'
      metrics_path: '/api/actuator/prometheus'
      static_configs:
        - targets: ['host.docker.internal:8081']
          labels:
            application: "Elara Email"

    - job_name: 'elara-login'
      metrics_path: '/api/actuator/prometheus'
      static_configs:
        - targets: ['host.docker.internal:8086']
          labels:
            application: "Elara Login"

    - job_name: 'elara-orders'
      metrics_path: '/api/actuator/prometheus'
      static_configs:
        - targets: ['host.docker.internal:8087']
          labels:
            application: "Elara Orders"

    - job_name: 'elara-payment'
      metrics_path: '/api/actuator/prometheus'
      static_configs:
        - targets: ['host.docker.internal:8090']
          labels:
            application: "Elara Payment"

    - job_name: 'elara-products'
      metrics_path: '/api/actuator/prometheus'
      static_configs:
        - targets: ['host.docker.internal:8084']
          labels:
            application: "Elara Prdoducts"

    - job_name: 'elara-products-get'
      metrics_path: '/api/actuator/prometheus'
      static_configs:
        - targets: ['host.docker.internal:8082']
          labels:
            application: "Elara Products Get"

    - job_name: 'elara-users'
      metrics_path: '/api/actuator/prometheus'
      static_configs:
        - targets: ['host.docker.internal:8085']
          labels:
            application: "Elara Users"
